# copy_firmware.py
# - erzeugt src/version.h aus build flags / platformio.ini (APP_VERSION)
# - registriert Post-Build actions auf mehreren Targets (elf, uf2, buildprog, upload)
# - falls schon vorhandene Artefakte existieren, erzeugt sofort die firmware/*.uf2.zip
import os
import shutil
import re
import zipfile
import glob
import configparser
from SCons.Script import Import

Import("env")

PROJECT_DIR = env.get("PROJECT_DIR")
PIOENV = env.get("PIOENV")
BUILD_DIR = env.get("BUILD_DIR")
PLATFORMIO_INI = os.path.join(PROJECT_DIR, "platformio.ini")

def read_version():
    # Try to read APP_VERSION from CPPDEFINES first
    cppdefs = env.get("CPPDEFINES") or []
    for d in cppdefs:
        # tuple ('APP_VERSION', 'v0.4') or string 'APP_VERSION="v0.4"'
        if isinstance(d, tuple) and d[0] == "APP_VERSION":
            return str(d[1]).strip()
        if isinstance(d, str) and d.startswith("APP_VERSION"):
            # e.g. APP_VERSION="v0.4" or APP_VERSION=v0.4
            val = d.split("=", 1)[1].strip().strip('"').strip("'")
            return val.strip()

    # Then try BUILD_FLAGS (may be string or list)
    bf = env.get("BUILD_FLAGS")
    if bf:
        if isinstance(bf, (list, tuple)):
            bf_str = " ".join(str(x) for x in bf)
        else:
            bf_str = str(bf)
        m = re.search(r'-DAPP_VERSION=(?:"|\')?(v?[0-9]+(?:\.[0-9]+)*)', bf_str)
        if m:
            return m.group(1).strip()

    # Finally try platformio.ini (legacy fallback)
    try:
        cfg = configparser.RawConfigParser()
        cfg.read(PLATFORMIO_INI)
        section_env = "env:" + (PIOENV or "")
        if cfg.has_option(section_env, "version"):
            return cfg.get(section_env, "version").strip()
        if cfg.has_section("env") and cfg.has_option("env", "version"):
            return cfg.get("env", "version").strip()
    except Exception:
        pass

    return None

def write_version_header(version):
    if not version:
        version = "0.0"
    header_path = os.path.join(PROJECT_DIR, "src", "version.h")
    os.makedirs(os.path.dirname(header_path), exist_ok=True)
    with open(header_path, "w", encoding="utf-8") as f:
        f.write("// generated by copy_firmware.py\n")
        f.write("#pragma once\n")
        f.write('#define APP_VERSION "{}"\n'.format(version))
    print(">>> generated", header_path, "with APP_VERSION =", version)
    return version

def find_artifact(build_dir, progname):
    # prefer uf2, then elf
    candidates = []
    if progname:
        candidates.append(os.path.join(build_dir, "{}.uf2".format(progname)))
        candidates.append(os.path.join(build_dir, "{}.elf".format(progname)))
    # glob fallback
    candidates.extend(glob.glob(os.path.join(build_dir, "*.uf2")))
    candidates.extend(glob.glob(os.path.join(build_dir, "*.elf")))
    for c in candidates:
        if os.path.exists(c):
            return c
    return None

def perform_copy(version, artifact_path):
    if not artifact_path:
        print(">>> perform_copy: no artifact found")
        return
    os.makedirs(os.path.join(PROJECT_DIR, "firmware"), exist_ok=True)
    base = "PicoServo-Tiny-V{}".format(version)
    ext = os.path.splitext(artifact_path)[1]
    dest_name = base + ext
    dest_file = os.path.join(PROJECT_DIR, "firmware", dest_name)
    try:
        shutil.copy(artifact_path, dest_file)
        print(">>> copied artifact to", dest_file)
    except Exception as e:
        print(">>> Error copying artifact:", e)
        return

    # process desc template
    tpl_candidates = glob.glob(os.path.join(PROJECT_DIR, "PicoServo-Tiny.desc"))
    if tpl_candidates:
        tpl = tpl_candidates[0]
        with open(tpl, "r", encoding="utf-8") as f:
            content = f.read()
        content = content.replace("{APP_VERSION}", version)
    else:
        content = "Name: PicoServo-Tiny\nVersion: {}\n".format(version)
        print(">>> no desc template found; creating minimal .desc")

    dest_desc = os.path.join(PROJECT_DIR, "firmware", base + ".desc")
    with open(dest_desc, "w", encoding="utf-8") as f:
        f.write(content)
    print(">>> wrote desc to", dest_desc)

    # create zip (use .uf2.zip name regardless of actual extension)
    zip_path = os.path.join(PROJECT_DIR, "firmware", base + ".uf2.zip")
    try:
        with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            zf.write(dest_file, arcname=os.path.basename(dest_file))
            zf.write(dest_desc, arcname=os.path.basename(dest_desc))
        print(">>> created zip", zip_path)
    except Exception as e:
        print(">>> Error creating zip:", e)

# main post-build wrapper compatible with SCons post action signature
def copy_firmware(source, target, env):
    print(">>> copy_firmware post-build running...")
    out_build_dir = env.subst("$BUILD_DIR")
    progname = env.subst("${PROGNAME}") or None
    print(">>> PROJECT_DIR:", PROJECT_DIR)
    print(">>> BUILD_DIR:", out_build_dir)
    print(">>> PROGNAME:", progname)

    artifact = find_artifact(out_build_dir, progname)
    if not artifact:
        print(">>> No artifact found in build dir - trying global search")
        artifact = find_artifact(out_build_dir, None)
    if not artifact:
        print(">>> Error: no UF2 or ELF found - aborting copy")
        return
    perform_copy(VERSION, artifact)

# read/generate version header now (pre-build)
RAW_VERSION = read_version()
if RAW_VERSION is None:
    print(">>> Warning: version not found; defaulting to 0.0")
VERSION = write_version_header(RAW_VERSION)

# register post actions on multiple targets to increase chance of execution
try:
    env.AddPostAction("$BUILD_DIR/${PROGNAME}.elf", copy_firmware)
    env.AddPostAction("$BUILD_DIR/${PROGNAME}.uf2", copy_firmware)
    env.AddPostAction("buildprog", copy_firmware)
    env.AddPostAction("upload", copy_firmware)
    print(">>> copy_firmware.py loaded; post actions registered for elf/uf2/buildprog/upload")
except Exception as e:
    print(">>> Warning: failed to register some post actions:", e)

# If artifacts already exist from a previous build, create firmware zip now
existing = find_artifact(os.path.join(PROJECT_DIR, BUILD_DIR), env.get("PROGNAME"))
if existing:
    print(">>> Existing build artifact detected at script load:", existing)
    perform_copy(VERSION, existing)
else:
    # also try BUILD_DIR as substituted variable
    bd = env.subst("$BUILD_DIR")
    existing2 = find_artifact(bd, env.subst("${PROGNAME}"))
    if existing2:
        print(">>> Existing build artifact detected at script load (alt):", existing2)
        perform_copy(VERSION, existing2)