[platformio]
src_dir = src
    
[env]
framework = arduino

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
Board = pico
board_build.core = earlephilhower
lib_deps =
    RP2040_PWM @ 1.7.0
    WS281xProcessor=file://..\..\..\libraries\WS281xProcessor @ 0.1
    MobaLedLib=     file://../../../libraries/MobaLedLib
    PicoFlashStorage=file://..\..\..\libraries\PicoFlashStorage @ 0.1
